name: 'Coverage'

on:
  pull_request:
    branches:
      - main

jobs:
  unittest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          # automatically cache dependencies using pnpm
          cache: "pnpm"
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          package-manager: pnpm
          github-token: ${{ secrets.GITHUB_TOKEN }}
